blog:
  build: blog
  container_name: randomblog
  command: "node app"
  volumes:
    - ./blog:/app
  ports:
    - "127.0.1.1:80:3000"

service:
  build: service
  command: "node app"
  volumes:
    - ./service:/app
  ports:
    - "127.0.1.2:80:3000"
